sudo: false
language: node_js
node_js:
  - '10'
  - '8'
  - '6'
before_install:
  - 'npm install -g npm@latest'
  - 'npm install -g greenkeeper-lockfile'
install: npm install
before_script: greenkeeper-lockfile-update
after_script:
  - npm run lint
  - npm run coveralls
  - greenkeeper-lockfile-upload
